package com.htt.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "tb_gps_location_record".
 */
public class GpsLocationRecordInfo {

    private Long id;
    private long recordTimes;
    private double latitued;
    private double longitude;
    private Long existTimes;
    private Float speed;
    private Float direction;
    private String locationInfo;

    public GpsLocationRecordInfo() {
    }

    public GpsLocationRecordInfo(Long id) {
        this.id = id;
    }

    public GpsLocationRecordInfo(Long id, long recordTimes, double latitued, double longitude, Long existTimes, Float speed, Float direction, String locationInfo) {
        this.id = id;
        this.recordTimes = recordTimes;
        this.latitued = latitued;
        this.longitude = longitude;
        this.existTimes = existTimes;
        this.speed = speed;
        this.direction = direction;
        this.locationInfo = locationInfo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getRecordTimes() {
        return recordTimes;
    }

    public void setRecordTimes(long recordTimes) {
        this.recordTimes = recordTimes;
    }

    public double getLatitued() {
        return latitued;
    }

    public void setLatitued(double latitued) {
        this.latitued = latitued;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public Long getExistTimes() {
        return existTimes;
    }

    public void setExistTimes(Long existTimes) {
        this.existTimes = existTimes;
    }

    public Float getSpeed() {
        return speed;
    }

    public void setSpeed(Float speed) {
        this.speed = speed;
    }

    public Float getDirection() {
        return direction;
    }

    public void setDirection(Float direction) {
        this.direction = direction;
    }

    public String getLocationInfo() {
        return locationInfo;
    }

    public void setLocationInfo(String locationInfo) {
        this.locationInfo = locationInfo;
    }

}
