package com.htt.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "tb_user_info".
 */
public class UserInfo {

    private Long id;
    /** Not-null value. */
    private String phone;
    /** Not-null value. */
    private String userName;
    /** Not-null value. */
    private String userPassword;

    public UserInfo() {
    }

    public UserInfo(Long id) {
        this.id = id;
    }

    public UserInfo(Long id, String phone, String userName, String userPassword) {
        this.id = id;
        this.phone = phone;
        this.userName = userName;
        this.userPassword = userPassword;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPhone() {
        return phone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /** Not-null value. */
    public String getUserName() {
        return userName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /** Not-null value. */
    public String getUserPassword() {
        return userPassword;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

}
